### ISSUE TITLE
does Orochi support loading both CUDA and HIP runtimes at the same time ?

### ISSUE THREAD

**Issue by fwyzard** [GPUOpen-LibrariesAndSDKs/Orochi#16]
From a quick look at the code, it seems that some parts do, while others do not.
For example, the initialisation and device handling seem to support enabling both CUDA and HIP at the same time, while the host memory allocation and registration functions work with only either one at a time.

**Comment by takahiroharada** [comment]
It does work. If you create amd and nvidia device on the same thread, you always need to call `oroCtxSetCurrent` before calling functions like `oroMalloc`. However, if you create a device per thread, it simply works without doing it as the api choice is stored per thread. 

We have some applications executing on amd and nvidia at the same time in a single app which is working totally fine.

**Comment by fwyzard** [comment]
Thanks !
