### ISSUE TITLE
Orochi support for Adrenalin 22.7.1 on Windows

### ISSUE THREAD

**Issue by FilipVaverka** [GPUOpen-LibrariesAndSDKs/Orochi#35]
Adrenalin 22.7.1 (driver version 31.0.12015.1008) seems to break Orochi as `amdhip64.dll` no longer exposes `hiprtc*` symbols. The driver doesn't seem to install `hiprtc.dll` either.

**Comment by takahiroharada** [comment]
This is a regression in the driver. A fix is in here which we'll merge soon. 

https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/pull/36

**Comment by takahiroharada** [comment]
Note that this dll may not be compatible with older driver. So we recommend to use it only with 22.7.1.

**Comment by takahiroharada** [comment]
A fix is implemented and merged. https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/pull/38

**Comment by oscarbg** [comment]
Hi,
curiously seems 22.8.1 is still missing hiprtc.dll also..
can use this dll on 22.8.1?
will take many time standard AMD drivers to include hiprtc.dll by default?
thanks..
