### ISSUE TITLE
hiprtc* symbols not found

### ISSUE THREAD

**Issue by ArturoBlas** [GPUOpen-LibrariesAndSDKs/Orochi#56]
Revision `f401a29869bc4eae64b0d10f3ae35e284cb42bf7` introduced a change to dynamically load `hiprtc0503.dll` as a replacement for `hiprtc.dll`, however this library is not currently shipped with recent AMD drivers (Adrenalin 22.10.2 and Enterprise 22.Q3).  Is there any other means to obtain this library?
Furthermore, these drivers remove from `amdhip64.dll ` all previously supported `hiprtc*` symbols on Adrenalin 22.5, which causes these symbols to be unresolved when accessing them via Orochi.

**Comment by takahiroharada** [comment]
The change is something HIP team decided to do unfortunately. I'm not a big fan of this change or regression TBH. The only way to get these hiprtc is from this Orochi repo at the moment. They will be also distributed through windows HIP SDK AMD is going to release in the future.

Btw, I'd like to know your application which got affected by this if you don't mind sharing.

**Comment by takahiroharada** [comment]
There is no plan for the driver to include them in the future. The only ways to get them are through this repo, or HIP SDK which will be released sometime in the future.
