### ISSUE TITLE
Textures Support?

### ISSUE THREAD

**Issue by TomClabault** [GPUOpen-LibrariesAndSDKs/Orochi#77]
I'm writing an application with HIPRT and Orochi. I'd like to use 2D textures but It seems like the function declarations are [commented out](https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/blob/main/Orochi/Orochi.h#L727).

Are textures not implemented in Orochi yet? Is the only alternative to use HIP?

**Comment by RichardGe** [comment]
Hi, 2D Texture support is currently work in progress. We don't have precise ETA, but should be there soon.

**Comment by TomClabault** [comment]
Is the graphicsMapResources() function family support also planned?

**Comment by RichardGe** [comment]
@TomClabault  , check the 2.0 release. It has texture management. graphicsMapResources also.
I added a added a demo here:
https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/tree/main/Test/Texture
