### ISSUE TITLE
Typos in some declarations: Suoroort -> Support

### ISSUE THREAD

**Issue by LtdJorge** [GPUOpen-LibrariesAndSDKs/Orochi#78]
I've found that there are some fields with "suoroort" in the name and comments instead of "support". Seems to me like it was caused by some automated renaming maybe?

The two types where it happens
- enum `oroDeviceAttribute` (in comments and fields)
- struct `oroDeviceProp` (only in comments)

I'm doing FFI from Rust and it's a bit annoying having the dirty names. Example: `oroDeviceAttributeHostNativeAtomicSuoroorted` in Orochi is `CU_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED` in CUDA.

**Comment by LtdJorge** [comment]
A different one: MipmaoroedArray -> MipmappedArray. Suggests the same replacing of "pp" for "oro".

**Comment by RichardGe** [comment]
the 2.0 release solves all those typos. thanks for the report.
